name: Coverage
on:
  push:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: x64
      - run: pip install nox==2020.12.31
      - run: pip install poetry==1.1.5
      - run: nox --sessions tests -- --cov-fail-under=100
      - run: nox --sessions coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
